# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'beta'
      version: 'latest'

  - script: flutter pub get
    displayName: 'Flutter: Get Packages'

  - script: flutter build apk
    displayName: 'Flutter: Build Android APK'
    condition: eq(variables['BuildPlatform'], 'Android')  # Run this step only if the build platform is Android

  - script: flutter build ios
    displayName: 'Flutter: Build iOS App'
    condition: eq(variables['BuildPlatform'], 'iOS')  # Run this step only if the build platform is iOS

  - script: flutter build web
    displayName: 'Flutter: Build Web App'
    condition: eq(variables['BuildPlatform'], 'Web')  # Run this step only if the build platform is Web

